import React from 'react';
import { Check, Image as ImageIcon, Link as LinkIcon, RotateCcw, Sparkles, Smile, Upload } from 'lucide-react';

export type FolderIconMode = 'presets' | 'upload' | 'url';
export const FOLDER_ICON_PRESETS = ['📁','📂','🤖','🎨','📖','🔮','💡','🍓','🎀','🍵','🌙','🧸','⚡','🌸','✨','💎','🎮','🦄','🎧','🧁','🚀','🔥','📚','⭐'];

interface FolderIconPickerProps {
  selectedIcon: string;
  iconMode: FolderIconMode;
  customEmojiInput: string;
  imageUrlInput: string;
  error: string;
  onIconChange: (value: string) => void;
  onModeChange: (mode: FolderIconMode) => void;
  onCustomEmojiChange: (value: string) => void;
  onImageUrlChange: (value: string) => void;
  onApplyEmoji: () => void;
  onApplyUrl: () => void;
  onFileUpload: (event: React.ChangeEvent<HTMLInputElement>) => void;
  onReset: () => void;
  fileInputRef: React.RefObject<HTMLInputElement | null>;
}

export const FolderIconPicker: React.FC<FolderIconPickerProps> = ({ selectedIcon, iconMode, customEmojiInput, imageUrlInput, onIconChange, onModeChange, onCustomEmojiChange, onImageUrlChange, onApplyEmoji, onApplyUrl, onFileUpload, onReset, fileInputRef }) => {
  const isImageIcon = selectedIcon.startsWith('data:image') || selectedIcon.startsWith('http');
  return <div className="space-y-2.5">
    <div className="flex items-center justify-between"><label className="text-xs font-bold text-slate-700 dark:text-slate-300 flex items-center gap-1.5"><Sparkles className="w-3.5 h-3.5 text-purple-600 dark:text-purple-400" /><span>ไอคอนโฟลเดอร์ (Icon / Image / GIF):</span></label><div className="flex items-center gap-2"><span className="text-[11px] text-slate-400">ตัวอย่าง:</span><div className="w-8 h-8 rounded-xl bg-white dark:bg-slate-800 border border-purple-200 dark:border-purple-700 shadow-xs flex items-center justify-center overflow-hidden">{isImageIcon ? <img src={selectedIcon} alt="Folder Icon Preview" className="w-full h-full object-cover" referrerPolicy="no-referrer" /> : <span className="text-base">{selectedIcon}</span>}</div>{isImageIcon && <button type="button" onClick={onReset} className="text-[10px] text-rose-500 hover:underline flex items-center gap-0.5 cursor-pointer" title="รีเซ็ตเป็นไอคอนปกติ"><RotateCcw className="w-2.5 h-2.5" /><span>รีเซ็ต</span></button>}</div></div>
    <div className="flex bg-slate-100 dark:bg-slate-800 p-1 rounded-xl gap-1"><button type="button" onClick={() => onModeChange('presets')} className={`flex-1 py-1.5 rounded-lg text-xs font-semibold flex items-center justify-center gap-1.5 transition-all cursor-pointer ${iconMode === 'presets' ? 'bg-white dark:bg-slate-700 text-purple-700 dark:text-purple-300 shadow-xs font-bold' : 'text-slate-500 hover:text-slate-800 dark:hover:text-slate-200'}`}><Smile className="w-3.5 h-3.5" /><span>อีโมจิ & พรีเซ็ต</span></button><button type="button" onClick={() => onModeChange('upload')} className={`flex-1 py-1.5 rounded-lg text-xs font-semibold flex items-center justify-center gap-1.5 transition-all cursor-pointer ${iconMode === 'upload' ? 'bg-white dark:bg-slate-700 text-purple-700 dark:text-purple-300 shadow-xs font-bold' : 'text-slate-500 hover:text-slate-800 dark:hover:text-slate-200'}`}><Upload className="w-3.5 h-3.5" /><span>อัปโหลดรูปภาพ / GIF</span></button><button type="button" onClick={() => onModeChange('url')} className={`flex-1 py-1.5 rounded-lg text-xs font-semibold flex items-center justify-center gap-1.5 transition-all cursor-pointer ${iconMode === 'url' ? 'bg-white dark:bg-slate-700 text-purple-700 dark:text-purple-300 shadow-xs font-bold' : 'text-slate-500 hover:text-slate-800 dark:hover:text-slate-200'}`}><LinkIcon className="w-3.5 h-3.5" /><span>วางลิงก์ URL</span></button></div>
    {iconMode === 'presets' && <div className="space-y-2"><div className="flex flex-wrap gap-1.5 p-2 bg-white dark:bg-slate-800/80 rounded-xl border border-purple-100 dark:border-purple-900/50">{FOLDER_ICON_PRESETS.map((icon, index) => <button key={index} type="button" onClick={() => onIconChange(icon)} className={`w-8 h-8 rounded-xl text-base flex items-center justify-center transition-all cursor-pointer ${selectedIcon === icon ? 'bg-purple-600 text-white shadow-xs scale-105 ring-2 ring-purple-300 dark:ring-purple-700' : 'bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-300 hover:bg-purple-100 dark:hover:bg-purple-950'}`}>{icon}</button>)}</div><div className="flex gap-2"><input type="text" value={customEmojiInput} onChange={(event) => onCustomEmojiChange(event.target.value)} placeholder="พิมพ์หรือวางอีโมจิ / Kaomoji อื่นๆ ที่ต้องการ..." className="flex-1 px-3 py-1.5 bg-white dark:bg-slate-800 border border-purple-100 dark:border-slate-700 rounded-xl text-xs text-slate-800 dark:text-slate-100" /><button type="button" onClick={onApplyEmoji} disabled={!customEmojiInput.trim()} className="px-3 py-1.5 bg-purple-600 hover:bg-purple-700 disabled:opacity-50 text-white text-xs font-semibold rounded-xl cursor-pointer">นำไปใช้</button></div></div>}
    {iconMode === 'upload' && <div className="space-y-2"><input type="file" ref={fileInputRef} onChange={onFileUpload} accept="image/*,.gif" className="hidden" /><div onClick={() => fileInputRef.current?.click()} className="border-2 border-dashed border-purple-200 dark:border-purple-800 hover:border-purple-400 bg-white dark:bg-slate-800/80 hover:bg-purple-50/50 rounded-2xl p-4 text-center cursor-pointer transition-all flex flex-col items-center justify-center gap-1.5"><div className="w-8 h-8 rounded-full bg-purple-100 dark:bg-purple-900/60 text-purple-600 dark:text-purple-300 flex items-center justify-center"><ImageIcon className="w-4 h-4" /></div><div><p className="text-xs font-bold text-purple-800 dark:text-purple-300">คลิกเพื่อเลือกไฟล์รูปภาพ หรือภาพ GIF เคลื่อนไหว</p><p className="text-[10.5px] text-slate-400">รองรับ PNG, JPG, WEBP, Animated GIF (ขนาดแนะนำสี่เหลี่ยมจัตุรัส ไม่เกิน 5MB)</p></div></div></div>}
    {iconMode === 'url' && <div className="space-y-2"><div className="flex gap-2"><input type="url" value={imageUrlInput} onChange={(event) => onImageUrlChange(event.target.value)} placeholder="https://example.com/icon.gif หรือ .png..." className="flex-1 px-3.5 py-2 bg-white dark:bg-slate-800 border border-purple-100 dark:border-slate-700 rounded-xl text-xs text-slate-800 dark:text-slate-100" /><button type="button" onClick={onApplyUrl} disabled={!imageUrlInput.trim()} className="px-4 py-2 bg-purple-600 hover:bg-purple-700 disabled:opacity-50 text-white text-xs font-bold rounded-xl cursor-pointer flex items-center gap-1"><Check className="w-3.5 h-3.5" /><span>นำไปใช้</span></button></div><p className="text-[10.5px] text-slate-400">💡 สามารถคัดลอกลิงก์ตรงของรูปภาพหรือ GIF จาก Discord, Tenor, Giphy, Pinterest หรือเว็บไซต์อื่นมาวางได้ทันที</p></div>}
  </div>;
};
